[project]
name = "tstomkv"
version = "0.1.2"
description = "A simple tool to convert TS files to MKV format over the network."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "types-toml>=0.10.8.20240310",
]
